#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const reporter = require('multiple-cucumber-html-reporter');

const testDir = path.resolve(__dirname, '..');
const reportsDir = path.join(testDir, 'reports');
const jsonReportPath = path.join(reportsDir, 'cucumber-report.json');
const htmlReportDir = path.join(reportsDir, 'html');
const jsAssetsDir = path.join(htmlReportDir, 'assets', 'js');
const reportBundleName = 'report.bundle.js';
const reporterTemplateJsDir = path.join(
  path.dirname(require.resolve('multiple-cucumber-html-reporter/package.json')),
  'templates',
  'assets',
  'js'
);

if (!fs.existsSync(jsonReportPath)) {
  console.error(`Cucumber JSON report not found: ${jsonReportPath}`);
  process.exit(1);
}

fs.mkdirSync(htmlReportDir, { recursive: true });

let perfAttachmentCount = 0;
try {
  const jsonReport = JSON.parse(fs.readFileSync(jsonReportPath, 'utf8'));
  const serialized = JSON.stringify(jsonReport);
  perfAttachmentCount = (serialized.match(/Performance Summary/g) || []).length;
} catch (error) {
  console.warn(`Failed to inspect performance attachment from cucumber JSON: ${String(error)}`);
}

reporter.generate({
  jsonDir: reportsDir,
  reportPath: htmlReportDir,
  pageTitle: 'Workforce Integration Test Report (Performance Included)',
  reportName: 'Workforce BDD Integration Report',
  displayDuration: true,
  pageFooter:
    '<div style="font-family: sans-serif;">Generated by workforce integration test harness - Performance metrics are attached per scenario.</div>',
  metadata: {
    browser: {
      name: 'N/A',
      version: 'N/A'
    },
    device: 'Containerized Integration Environment',
    platform: {
      name: 'Docker',
      version: 'compose'
    }
  }
});

const bundleSources = [
  'darkmode.js',
  'jquery.min.js',
  'bootstrap.min.js',
  'Chart.min.js',
  'datatables.jquery.min.js',
  'datatables.min.js',
  'datatables.bootstrap5.min.js',
  'dataTables.responsive.min.js',
  'responsive.bootstrap5.js'
];

const buildSingleJsBundle = () => {
  const sections = [];

  for (const fileName of bundleSources) {
    const fullPath = path.join(reporterTemplateJsDir, fileName);
    if (!fs.existsSync(fullPath)) {
      console.warn(`Skipped missing JS asset while bundling: ${fileName}`);
      continue;
    }
    const content = fs.readFileSync(fullPath, 'utf8');
    sections.push(`/* ${fileName} */\n${content}\n`);
  }

  if (sections.length === 0) {
    console.warn('No JS assets were bundled; keeping generated script references as-is.');
    return false;
  }

  fs.mkdirSync(jsAssetsDir, { recursive: true });
  const bundlePath = path.join(jsAssetsDir, reportBundleName);
  fs.writeFileSync(bundlePath, `${sections.join('\n')}\n`, 'utf8');

  const existingJsFiles = fs.readdirSync(jsAssetsDir).filter((name) => name.endsWith('.js'));
  for (const name of existingJsFiles) {
    if (name !== reportBundleName) {
      fs.rmSync(path.join(jsAssetsDir, name), { force: true });
    }
  }

  return true;
};

const rewriteHtmlToUseBundle = (htmlFilePath) => {
  const htmlDir = path.dirname(htmlFilePath);
  const bundleRelativePath = path.relative(htmlDir, path.join(jsAssetsDir, reportBundleName)).replace(/\\/g, '/');

  let html = fs.readFileSync(htmlFilePath, 'utf8');
  const legacyScriptPattern = /<script\s+src="(?:\.\.\/)?assets\/js\/[^"]+\.js"><\/script>\s*/g;
  html = html.replace(legacyScriptPattern, '');
  html = html.replace(/<!--\[if lt IE 9\]>[\s\S]*?<!\[endif\]-->\s*/g, '');

  const bundleTag = `<script src="${bundleRelativePath}"></script>\n`;
  if (html.includes('<!-- Custom -->')) {
    html = html.replace('<!-- Custom -->', `${bundleTag}\n    <!-- Custom -->`);
  } else if (html.includes('</body>')) {
    html = html.replace('</body>', `${bundleTag}</body>`);
  } else {
    html += `\n${bundleTag}`;
  }

  fs.writeFileSync(htmlFilePath, html, 'utf8');
};

if (buildSingleJsBundle()) {
  const htmlFiles = [];
  const walk = (dirPath) => {
    const entries = fs.readdirSync(dirPath, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dirPath, entry.name);
      if (entry.isDirectory()) {
        walk(fullPath);
      } else if (entry.isFile() && entry.name.endsWith('.html')) {
        htmlFiles.push(fullPath);
      }
    }
  };

  walk(htmlReportDir);
  for (const htmlFilePath of htmlFiles) {
    rewriteHtmlToUseBundle(htmlFilePath);
  }

  console.log(`Bundled report JS into: ${path.join('assets', 'js', reportBundleName)}`);
}

if (perfAttachmentCount === 0) {
  console.warn('No performance attachments were detected in cucumber-report.json.');
} else {
  console.log(`Detected performance attachments: ${perfAttachmentCount}`);
}

console.log(`HTML report generated: ${path.join(htmlReportDir, 'index.html')}`);
